version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lphenom-http-dev:latest
    container_name: lphenom_http_app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - COMPOSER_HOME=/tmp/composer
    tty: true
    stdin_open: true

